/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#000000",
        "on-primary": "#ffffff",
        ink: "#000000",
        "ink-deep": "#090909",
        charcoal: "#525252",
        body: "#737373",
        mute: "#a3a3a3",
        canvas: "#ffffff",
        "surface-soft": "#fafafa",
        "surface-card": "#ffffff",
        hairline: "#e5e5e5",
        "hairline-strong": "#d4d4d4",
        "on-dark": "#ffffff",
        "surface-dark": "#171717",
        "focus-ring": "rgba(59,130,246,0.5)",
        "terminal-red": "#ff5f56",
        "terminal-yellow": "#ffbd2e",
        "terminal-green": "#27c93f",
        border: "var(--border)",
      },
      fontFamily: {
        display: [
          "SF Pro Rounded",
          "Nunito",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        sans: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      fontSize: {
        "display-xl": ["36px", { lineHeight: "1.11", fontWeight: "500" }],
        "display-lg": ["30px", { lineHeight: "1.2", fontWeight: "500" }],
        "heading-lg": ["24px", { lineHeight: "1.33", fontWeight: "600" }],
        "heading-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "heading-sm": ["18px", { lineHeight: "1.56", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.43", fontWeight: "400" }],
        "caption-sm": ["12px", { lineHeight: "1.33", fontWeight: "400" }],
        "code-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "code-sm": ["14px", { lineHeight: "1.43", fontWeight: "400" }],
        "button-md": ["14px", { lineHeight: "1", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        full: "9999px",
      },
      spacing: {
        section: "88px",
        "section-md": "64px",
        "section-sm": "48px",
      },
      maxWidth: {
        content: "720px",
        wide: "960px",
      },
      height: {
        nav: "56px",
        pill: "36px",
        snippet: "48px",
      },
    },
  },
  plugins: [],
}
